port:
  - 9095
pathNames:
  - C:\Users\harvey.liu\Documents\WeChat Files\wxid_qym9bp21lk8y32\FileStorage\File\2022-01\变更方案&其他文档
  - C:\Users\harvey.liu\Documents\WeChat Files\wxid_qym9bp21lk8y32\FileStorage\File\2022-01\变更方案&其他文档\亿赛通操作手册
servicePorts:
  - 8080
  - 443
  - 4444